name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Manuscript
    runs-on: ubuntu-latest
    shell: bash --login {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Build Manuscript
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript.pdf
          path: output
      - name: Deploy
        if: (
          github.ref == 'refs/heads/master' &&
          github.event_name == 'push' &&
          job.status == 'success')
        env:
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
        run: bash ci/deploy.sh
