name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Manuscript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Build Manuscript
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript.pdf
          path: output/manuscript.pdf
      - name: Deploy
        if: (
          github.ref == 'refs/heads/master' &&
          github.event_name == 'push' &&
          job.status == 'success')
        env:
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
          BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
          JOB_WEB_URL: https://github.com/$GITHUB_REPOSITORY/runs/$GITHUB_ACTION
        shell: bash --login {0}        
        run: bash ci/deploy.sh
